entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver
        options:
          default:
            minVersion: VersionTLS12
            cipherSuites:
              - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
              - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
              - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
              - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
              - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
              - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA

certificatesResolvers:
  myresolver:
    acme:
      email: "{{ EMAIL }}"
      storage: "/letsencrypt/acme.json"
      tlsChallenge: true

api:
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
